"""init

Revision ID: 399ee63fc892
Revises: 2561a2e7a73e
Create Date: 2019-12-16 22:52:07.311323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399ee63fc892'
down_revision = '2561a2e7a73e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email_confirmation_sent_on', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('email_confirmed', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email_confirmed_on', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed_on')
    op.drop_column('users', 'email_confirmed')
    op.drop_column('users', 'email_confirmation_sent_on')
    op.drop_column('users', 'authenticated')
    # ### end Alembic commands ###
