"""init

Revision ID: 70ef13f25b61
Revises: 399ee63fc892
Create Date: 2019-12-17 10:39:52.588213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ef13f25b61'
down_revision = '399ee63fc892'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
