"""init

Revision ID: 51fe48fd1a4a
Revises: 70ef13f25b61
Create Date: 2019-12-27 23:10:43.104656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fe48fd1a4a'
down_revision = '70ef13f25b61'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    op.add_column('users', sa.Column('email', sa.Text(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.drop_constraint('uq_users_name', 'users', type_='unique')
    op.drop_column('users', 'authenticated')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.TEXT(), nullable=False))
    op.add_column('users', sa.Column('authenticated', sa.INTEGER(), nullable=True))
    op.create_unique_constraint('uq_users_name', 'users', ['name'])
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_column('users', 'email')
    op.create_table('pages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='fk_pages_creator_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_pages'),
    sa.UniqueConstraint('name', name='uq_pages_name')
    )
    # ### end Alembic commands ###
